
version: '3.8'
services:
  script:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - script_db
  script_db:
    image: postgres
    container_name: script_db
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - .dbdata:/var/lib/postgresql/data
    ports:
      - 33066:3306